name: test-build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.x
      - name: Checkout code
        uses: actions/checkout@v1
      - name: build
        run: |
          export GO111MODULE=on
          GOOS=windows GOARCH=amd64 go build -o bin/magic-home-windows-amd64.exe
          GOOS=linux   GOARCH=amd64 go build -o bin/magic-home-linux-amd64
          GOOS=darwin  GOARCH=amd64 go build -o bin/magic-home-darwin-amd64
      - name: upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: binaries
          path: bin/
